"""Updated bildup_user_id to just user id

Revision ID: 5c7aaf06499b
Revises: 902a6ce4ce51
Create Date: 2025-11-25 16:06:36.805974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c7aaf06499b'
down_revision: Union[str, Sequence[str], None] = '902a6ce4ce51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('users_bildup_user_id_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['user_id'])
    op.drop_column('users', 'bildup_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bildup_user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_bildup_user_id_key'), 'users', ['bildup_user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
