"""initial first migration after setup of tables

Revision ID: 6478873b249c
Revises:
Create Date: 2025-10-23 06:02:40.458885

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from app.models import GUID

# revision identifiers, used by Alembic.
revision: str = "6478873b249c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "production_tasks",
        sa.Column("task_name", sa.String(), nullable=True),
        sa.Column("run_count", sa.Numeric(), nullable=True),
        sa.Column("max_runs", sa.Numeric(), nullable=True),
        sa.Column("id", GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_fake", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("bildup_user_id", sa.String(), nullable=False),
        sa.Column("is_ai", sa.Boolean(), nullable=True),
        sa.Column("user_info", sa.JSON(), nullable=True),
        sa.Column("id", GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_fake", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bildup_user_id"),
    )
    op.create_table(
        "rooms",
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "room_type", sa.Enum("PUBLIC", "PRIVATE", name="roomtype"), nullable=False
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_locked", sa.Boolean(), nullable=True),
        sa.Column("created_by_user_id", GUID(), nullable=False),
        sa.Column("id", GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_fake", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "messages",
        sa.Column("room_id", GUID(), nullable=False),
        sa.Column("user_id", GUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "message_type",
            sa.Enum("TEXT", "IMAGE", "VIDEO", "FILE", name="messagetype"),
            nullable=False,
        ),
        sa.Column("reply_to_id", GUID(), nullable=True),
        sa.Column("id", GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_fake", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reply_to_id"],
            ["messages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "room_members",
        sa.Column("room_id", GUID(), nullable=False),
        sa.Column("user_id", GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("room_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("room_members")
    op.drop_table("messages")
    op.drop_table("rooms")
    op.drop_table("users")
    op.drop_table("production_tasks")
    # ### end Alembic commands ###
