"""Added classroom id the room creation

Revision ID: 902a6ce4ce51
Revises: 6478873b249c
Create Date: 2025-10-24 17:21:24.462990

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from app.models import GUID

# revision identifiers, used by Alembic.
revision: str = "902a6ce4ce51"
down_revision: Union[str, Sequence[str], None] = "6478873b249c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rooms", sa.Column("bildup_classroom_id", GUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rooms", "bildup_classroom_id")
    # ### end Alembic commands ###
